dist: trusty
sudo: required
language: node_js
node_js:
  - "8.9.3"
  - "8"
  - "7"
  - "lts/*"
before_install:
  - npm install
before_script:
  - cp .test.env .env
  - chmod +x ./cli.js
  - ./cli.js key:generate
  - sudo apt-get update -y && sudo apt-get upgrade -y
  - sudo apt-get install update-manager-core -y
  - sudo do-release-upgrade -y
  - sudo psql -c 'CREATE DATABASE test;' -U postgres
  - sudo psql -c "CREATE USER test WITH PASSWORD 'test';" -U postgres
cache:
  directories:
    - "node_modules"
services:
  - postgresql