dist: trusty
sudo: required
language: node_js
node_js:
  - "8.9.3"
  - "8"
  - "7"
before_install:
  - sudo service postgresql stop
  - sudo cp /etc/postgresql/9.6/main/pg_hba.conf /pg_hba.conf
  - sudo apt-get --purge remove postgresql\*
  - sudo apt autoremove
  - sudo apt-get upgrade -y
  - sudo apt-get update -y --fix-missing
  - sudo apt-get install postgresql-10
  - sudo cp /pg_hba.conf /etc/postgresql/10/main/pg_hba.conf
  - sudo cat /etc/postgresql/10/main/pg_hba.conf
  - sudo service postgresql restart
  - npm install
before_script:
  - sudo psql -c 'CREATE DATABASE test;' -U postgres
  - sudo psql -c "CREATE USER test WITH PASSWORD 'test';" -U postgres
  - cp .test.env .env
  - chmod +x ./cli.js
  - ./cli.js key:generate
cache:
  directories:
    - "node_modules"
addon:
  posgtgres: "10"
