language: node_js
node_js:
  - "8.9.3"
  - "8"
  - "7"
  - "lts/*"
before_install:
  - npm install
before_script:
  - cp .test.env .env
  - chmod +x ./cli.js
  - ./cli.js key:generate
  - psql -c 'create database test;' -U postgres
  - psql -c "CREATE USER test WITH PASSWORD 'test';" -U postgres
cache:
  directories:
    - "node_modules"
services:
  - postgresql
addons:
  postgresql: "10.1"